version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: bzfuser
      POSTGRES_PASSWORD: bzfpassword
      POSTGRES_DB: bzftrainer
    ports:
      - "5433:5432"
    volumes:
      - bzf-db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://bzfuser:bzfpassword@db:5432/bzftrainer
      PDF_PATH: /data/questions.pdf
    depends_on:
      - db
    volumes:
      - C:/Users/yanni/Downloads/2024Pruefungsfragen_BZFII_BZFI_pdf.pdf:/data/questions.pdf

  frontend:
    build: ./frontend
    ports:
      - "5123:80"
    depends_on:
      - backend

volumes:
  bzf-db-data:
